[project]
name = "veda-features-api-cdk"
version = "0.1.0"
description = "Infrastructure for the VEDA features API"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
  "aws-cdk-lib==2.149.0",
  "constructs>=10.0.0,<11.0.0",
  "pydantic==2.8.2",
  "pydantic-settings==2.3.4",
  "aws-cdk.aws_apigatewayv2_alpha~=2.47.0.a0",
  "aws_cdk.aws_apigatewayv2_integrations_alpha~=2.47.0.a0",
]

[dependency-groups]
dev = [
  "pre-commit==4.6.2"
]

[tool.uv]
default-groups = ["dev"]

[tool.ruff]
line-length = 88

[tool.ruff.lint]
select = [
    "E",    # pycodestyle errors
    "W",    # pycodestyle warnings
    "F",    # Pyflakes
    "I",    # isort
    "UP",   # pyupgrade
    "B",    # flake8-bugbear
    "C4",   # flake8-comprehensions
    "SIM",  # flake8-simplify
    "PTH",  # flake8-use-pathlib
    "RET",  # flake8-return
    "TID",  # flake8-tidy-imports
    "TC",   # flake8-type-checking
    "ISC",  # flake8-implicit-str-concat
    "ICN",  # flake8-import-conventions
]
ignore = [
  "BLE001",  # Blind Exceptions
]

[tool.ruff.format]
docstring-code-format = true
docstring-code-line-length = "dynamic"

[tool.markdownlint-cli2.config]
MD013 = false
MD033 = { allowed_elements = ["a", "b", "details", "summary"] }
