name: Deploy features-api

inputs:
  env_aws_secret_name:
    required: true
    type: string
  script_path:
    type: string
  dir:
    required: false
    type: string
    default: "."

runs:
  using: "composite"
  steps:

    - name: Checkout code
      uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0

    - name: Install uv
      uses: astral-sh/setup-uv@c771a70e6277c0a99b617c7a806ffedaca235ff9 # v9.0.0
      with:
        enable-cache: true

    - name: Install dependencies
      shell: bash
      working-directory: ${{ inputs.dir }}
      run: |
        make install

    - name: Get relevant environment configuration from aws secrets
      shell: bash
      working-directory: ${{ inputs.dir }}
      env:
        AWS_DEFAULT_REGION: us-west-2
      run: |
        if [ -z "${{ inputs.script_path }}" ]
          then
            ./scripts/sync-env-local.sh ${{ inputs.env_aws_secret_name }}
          else
            python ${{ inputs.script_path }} --secret-id ${{ inputs.env_aws_secret_name }}
        fi

    - name: Deploy
      shell: bash
      working-directory: ${{ inputs.dir }}
      run: |
        echo $STAGE
        make deploy ARGS="--require-approval never --outputs-file ${HOME}/cdk-outputs.json"
