name: CDK Deploy Dev Workflow 🚀

on:
  push:
    branches:
      - main

jobs:
  define-environment:
    name: Set ✨ environment ✨
    runs-on: ubuntu-latest
    steps:
      - name: Set the environment based on the branch
        id: define_environment
        run: |
          if [ "${{ github.ref }}" = "refs/heads/main" ]; then
            echo "env_name=dev" >> $GITHUB_OUTPUT
          fi
      - name: Print the environment
        run: echo "The environment is ${{ steps.define_environment.outputs.env_name }}"

    outputs:
      env_name: ${{ steps.define_environment.outputs.env_name }}

  deploy:
    name: Deploy to ${{ needs.define-environment.outputs.env_name }} 🚀
    runs-on: ubuntu-latest
    if: ${{ needs.define-environment.outputs.env_name }}
    needs: [define-environment]
    permissions:
      id-token: write
      contents: read
    environment: ${{ needs.define-environment.outputs.env_name }}
    concurrency: ${{ needs.define-environment.outputs.env_name }}

    steps:
      - name: Checkout
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          lfs: true
          submodules: false
          persist-credentials: false

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@e6de054238d6b7531b4efff3b6587d9aade6a06c #v6.2.3
        with:
          role-to-assume: ${{ secrets.DEPLOYMENT_ROLE_ARN }}
          role-session-name: "veda-features-api-github-${{ needs.define-environment.outputs.env_name }}-deployment"
          aws-region: us-west-2

      - name: Run veda-features-api deployment
        uses: "./.github/actions/cdk-deploy"
        with:
          env_aws_secret_name: ${{ vars.ENV_AWS_SECRET_NAME }}
